name: client
description: MindBloom Mental Health App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests
  http: ^1.1.0

  # Save token locally
  shared_preferences: ^2.2.0

  # State management
  provider: ^6.1.0

  # Charts
  fl_chart: ^0.66.0

  # Icons
  cupertino_icons: ^1.0.8

  # Open phone dialer / SMS / browser (result screen support buttons)
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/hero_meditation.png
    - assets/images/logo.png